*****************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.             *
*   NEVER CHANGE IT MANUALLY, PLEASE!                           *
*****************************************************************
INCLUDE LZSOL_TRADEXU01.
                    "ZSOL_BAPI_GET_QLTY_PARAM
INCLUDE LZSOL_TRADEXU02.
                    "ZSOL_BAPI_UPDATE_QLTY_PARAM
INCLUDE LZSOL_TRADEXU03.
                    "ZSOL_BAPI_CHAR_NUMBER_CONV
